import os
from typing import Optional

CONFIG_PATH = os.path.join(os.path.dirname(__file__), 'config.py')


def _escape(value: Optional[str]) -> str:
	if value is None:
		return ""
	return str(value).replace("\\", "\\\\").replace('"', '\\"')


def save_to_config_py(openai_key: Optional[str] = None,
					   fb_app_id: Optional[str] = None,
					   fb_app_secret: Optional[str] = None,
					   fb_access_token: Optional[str] = None,
					   fb_ad_account_id: Optional[str] = None,
					   fb_page_id: Optional[str] = None) -> str:
	"""
	Writes credentials to config.py. Overwrites existing file.
	Returns the written file path.
	"""
	content = [
		"# config.py (generated by Settings UI)\n",
		"# DO NOT COMMIT THIS FILE. It is listed in .gitignore.\n\n",
		f'OPENAI_API_KEY = "{_escape(openai_key)}"\n',
		f'FACEBOOK_APP_ID = "{_escape(fb_app_id)}"\n',
		f'FACEBOOK_APP_SECRET = "{_escape(fb_app_secret)}"\n',
		f'FACEBOOK_ACCESS_TOKEN = "{_escape(fb_access_token)}"\n',
		f'FACEBOOK_AD_ACCOUNT_ID = "{_escape(fb_ad_account_id)}"\n',
		f'FACEBOOK_PAGE_ID = "{_escape(fb_page_id)}"\n',
	]
	data = ''.join(content)
	# Write with 0600 permissions
	tmp_path = CONFIG_PATH + ".tmp"
	with open(tmp_path, 'w') as f:
		f.write(data)
	os.chmod(tmp_path, 0o600)
	os.replace(tmp_path, CONFIG_PATH)
	return CONFIG_PATH